"""Adds site reference to ScannerMainUrl

Revision ID: 1183d4d75252
Revises: 8dd9e582a2a0
Create Date: 2024-05-16 23:14:17.408695

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1183d4d75252'
down_revision = '8dd9e582a2a0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('scanner_main_url', schema=None) as batch_op:
        batch_op.add_column(sa.Column('site_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'site', ['site_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('scanner_main_url', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('site_id')

    # ### end Alembic commands ###
