"""Removes user from ScannerMainUrl

Revision ID: fe48918d2dce
Revises: 1183d4d75252
Create Date: 2024-05-16 23:17:02.053063

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fe48918d2dce'
down_revision = '1183d4d75252'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('scanner_main_url', schema=None) as batch_op:
        batch_op.drop_constraint('scanner_main_url_user_id_fkey', type_='foreignkey')
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('scanner_main_url', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.create_foreign_key('scanner_main_url_user_id_fkey', 'user', ['user_id'], ['id'])

    # ### end Alembic commands ###
