"""Adds created_at and updated_at columns to SiteAddedSources

Revision ID: 259d19983d21
Revises: 59c921f96585
Create Date: 2024-06-07 22:04:50.433917

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '259d19983d21'
down_revision = '59c921f96585'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('site_added_sources', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=False))
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('site_added_sources', schema=None) as batch_op:
        batch_op.drop_column('updated_at')
        batch_op.drop_column('created_at')

    # ### end Alembic commands ###
