"""Added created_at and updated_at to Site

Revision ID: 44567d90f57b
Revises: 4a1616e2c867
Create Date: 2024-05-24 23:23:28.053378

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '44567d90f57b'
down_revision = '4a1616e2c867'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('site', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=True))

    # Execute the update statement outside of the batch_alter_table context
    op.execute("UPDATE site SET created_at = NOW(), updated_at = NOW()")

    # Alter the column to make it non-nullable
    with op.batch_alter_table('site', schema=None) as batch_op:
        batch_op.alter_column('created_at', nullable=False)
        batch_op.alter_column('updated_at', nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('site', schema=None) as batch_op:
        batch_op.drop_column('updated_at')
        batch_op.drop_column('created_at')

    # ### end Alembic commands ###
