"""Adds max_sites to user table

Revision ID: 4a1616e2c867
Revises: fe48918d2dce
Create Date: 2024-05-17 18:55:10.866832

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4a1616e2c867'
down_revision = 'fe48918d2dce'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('max_sites', sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('max_sites')

    # ### end Alembic commands ###
