"""Removes Main and Scanned urls tables in favour of singular SiteAddedSources table

Revision ID: 59c921f96585
Revises: ce23f95b5a15
Create Date: 2024-06-07 20:29:54.271085

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '59c921f96585'
down_revision = 'ce23f95b5a15'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('site_sources')
    
    with op.batch_alter_table('site', schema=None) as batch_op:
        batch_op.add_column(sa.Column('favicon_url', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('max_urls_allowed', sa.Integer(), nullable=True))

    # Set default value for existing rows where max_urls_allowed is NULL
    op.execute('UPDATE site SET max_urls_allowed = 100 WHERE max_urls_allowed IS NULL')

    # Alter column to make it non-nullable
    with op.batch_alter_table('site', schema=None) as batch_op:
        batch_op.alter_column('max_urls_allowed', nullable=False)

    with op.batch_alter_table('site_added_sources', schema=None) as batch_op:
        batch_op.add_column(sa.Column('type', sa.String(length=80), nullable=True))
        batch_op.alter_column('source_type',
               existing_type=sa.VARCHAR(length=80),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('site_added_sources', schema=None) as batch_op:
        batch_op.alter_column('source_type',
               existing_type=sa.VARCHAR(length=80),
               nullable=True)
        batch_op.drop_column('type')

    with op.batch_alter_table('site', schema=None) as batch_op:
        batch_op.drop_column('max_urls_allowed')
        batch_op.drop_column('favicon_url')

    op.create_table('site_sources',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('site_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('type', sa.VARCHAR(length=80), autoincrement=False, nullable=False),
    sa.Column('content_type', sa.VARCHAR(length=80), autoincrement=False, nullable=True),
    sa.Column('source', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['site_id'], ['site.id'], name='site_sources_site_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='site_sources_pkey')
    )
    # ### end Alembic commands ###
