"""empty message

Revision ID: 5ddb6f77cc09
Revises: 9a3863ae651d
Create Date: 2024-06-25 22:55:24.615227

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5ddb6f77cc09'
down_revision = '9a3863ae651d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chat_message', schema=None) as batch_op:
        batch_op.add_column(sa.Column('level', sa.String(length=30), nullable=False))
        batch_op.alter_column('room',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=80),
               existing_nullable=False)
        batch_op.alter_column('sender',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=120),
               existing_nullable=False)
        batch_op.drop_column('site_id')
        batch_op.drop_column('user_id')

    with op.batch_alter_table('site_added_sources', schema=None) as batch_op:
        batch_op.alter_column('source',
               existing_type=sa.VARCHAR(length=80),
               type_=sa.String(length=2048),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('site_added_sources', schema=None) as batch_op:
        batch_op.alter_column('source',
               existing_type=sa.String(length=2048),
               type_=sa.VARCHAR(length=80),
               existing_nullable=False)

    with op.batch_alter_table('chat_message', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('site_id', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
        batch_op.alter_column('sender',
               existing_type=sa.String(length=120),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
        batch_op.alter_column('room',
               existing_type=sa.String(length=80),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
        batch_op.drop_column('level')

    # ### end Alembic commands ###
