"""Added type to scanner_found_urls

Revision ID: ce23f95b5a15
Revises: 44567d90f57b
Create Date: 2024-05-29 14:14:00.580368

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ce23f95b5a15'
down_revision = '44567d90f57b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('scanner_found_urls', schema=None) as batch_op:
        batch_op.add_column(sa.Column('type', sa.String(length=80), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('scanner_found_urls', schema=None) as batch_op:
        batch_op.drop_column('type')

    # ### end Alembic commands ###
